# Generated by Django 6.0.4 on 2026-05-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='permission',
            field=models.TextField(help_text='According to the role you will get permissions.'),
        ),
    ]
