# Generated by Django 6.0.4 on 2026-05-10 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FutsalCourt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court', models.CharField(max_length=50)),
                ('location', models.CharField(help_text='Shantinagar, Kathmandu', max_length=50)),
                ('base_price', models.DecimalField(decimal_places=2, help_text='morning/mid/night rate', max_digits=10)),
                ('surface_type', models.CharField(help_text='5A, 7A side futsal', max_length=50)),
                ('status', models.CharField(choices=[('open', 'OPEN'), ('maintenance', 'MAINTENANCE'), ('closed', 'CLOSED')], default='open', max_length=100)),
                ('city_area', models.CharField(help_text='Kathmandu, Lalitpur, Bhaktapur', max_length=50)),
                ('phone_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('total_booking_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('booking_status', models.CharField(default='pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_timestamp', models.DateTimeField(auto_now_add=True)),
                ('PaymentMethod', models.CharField(choices=[('esewa', 'ESEWA'), ('khalti', 'KHALTI'), ('bank', 'BANK'), ('cash', 'CASH')], max_length=50)),
                ('PaymentStatus', models.CharField(choices=[('pending', 'PENDING'), ('completed', 'COMPLETED'), ('failed', 'FAILED')], default='PENDING', max_length=20)),
                ('TransactionHash', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='bookings.booking')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('date', models.DateField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeslots', to='bookings.futsalcourt')),
            ],
        ),
        migrations.CreateModel(
            name='BookingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_slots', to='bookings.booking')),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_times', to='bookings.timeslot')),
            ],
        ),
    ]
