# Generated by Django 6.0.4 on 2026-05-12 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_timestamp',
            new_name='payment_date',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='PaymentMethod',
            new_name='payment_methods',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='PaymentStatus',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('completed', 'COMPLETED'), ('failed', 'FAILED')], default='pending', max_length=20),
        ),
    ]
