# Generated by Django 6.0.4 on 2026-05-28 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_rename_payment_timestamp_payment_payment_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='futsalcourt',
            old_name='court',
            new_name='court_name',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='TransactionHash',
            new_name='transaction_hash',
        ),
        migrations.RemoveField(
            model_name='futsalcourt',
            name='status',
        ),
        migrations.AddField(
            model_name='booking',
            name='advance_deposit',
            field=models.DecimalField(decimal_places=2, default=200.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='due_later',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='futsalcourt',
            name='court_status',
            field=models.CharField(choices=[('open', 'Open'), ('maintenance', 'Maintenance'), ('closed', 'Closed'), ('school', 'School events'), ('booked', 'tournament events is going on')], default='open', max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('confirmed', 'CONFIRMED'), ('cancelled', 'CANCELLED')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bookings.booking'),
        ),
    ]
