# Generated by Django 6.0.4 on 2026-06-15 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_rename_court_futsalcourt_court_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='futsalcourt',
            name='city_area',
            field=models.CharField(help_text='Kathmandu, Lalitpur, Bhaktapur', max_length=30),
        ),
        migrations.AlterField(
            model_name='futsalcourt',
            name='court_status',
            field=models.CharField(choices=[('open', 'Open'), ('maintenance', 'Maintenance'), ('closed', 'Closed'), ('school', 'School events'), ('booked', 'tournament events is going on')], default='Open', max_length=100),
        ),
        migrations.CreateModel(
            name='BookingCancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.IntegerField()),
                ('court_name', models.CharField(max_length=150)),
                ('slot_date', models.DateField()),
                ('slot_range', models.CharField(max_length=100)),
                ('cancellation_type', models.CharField(choices=[('sinlge', 'single slot cancellation'), ('entire', 'entire slot cancellation')], max_length=20)),
                ('cancelled_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_cancellation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
