# Generated by Django 6.0.4 on 2026-06-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_futsalcourt_city_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futsalcourt',
            name='court_status',
            field=models.CharField(choices=[('open', 'Open'), ('maintenance', 'Maintenance'), ('closed', 'Closed'), ('school', 'School events'), ('booked', 'tournament events is going on')], default='open', max_length=100),
        ),
    ]
