# Generated by Django 6.0.4 on 2026-06-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_futsalcourt_court_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='advance_deposit',
            field=models.DecimalField(decimal_places=2, default=300, max_digits=10),
        ),
    ]
